
  version: smartide/v0.2
  orchestrator:
    type: docker-compose
    version: 3
  workspace:
    dev-container:
      service-name: vue-element-admin
      webide-port: 6800
      ide-type: vscode  #vscode/theia
      volumes: 
        git-config: true
        ssh-key: true
    services:
  
      vue-element-admin:
        image: registry.cn-hangzhou.aliyuncs.com/smartide/smartide-opvscode:latest
        restart: always
        volumes:
          - .:/home/project
        expose:
          - 3000
        ports:
          - 9588:9588
        networks:
          - smartide-network
  
    networks:
      smartide-network:
        external: true


